name: Test site build

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk

jobs:
  test_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Build
        run: chmod +x build-site.sh && ./build-site.sh
        env:
          SELENIUM_CI_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
